### ISSUE TITLE
i wanna send data that received from the pub/sub function to the firebase realtime database? did i have to create a second function with google coloud or addev to the first one ?

### ISSUE THREAD

**Issue by hanadjerbi1** [GabeWeiss/GoogleIoTCoreApp#5]

**Comment by GabeWeiss** [comment]
If you want to use Firebase instead of Firestore, then yes, you'll modify the Cloud Function to using the Firebase API instead, which is similar to Firestore, but different enough that it'll be a bit of porting work. The docs for Firebase can be found here: https://firebase.corp.google.com/ and click through to the documentation. OR you can just start a project in Firebase, and it will have getting started on the web on the home page for the real time database, and you can copy/paste the startup code from there to get going!

**Comment by hanadjerbi1** [comment]
thanks for replying me..But i can't get access to this link  https://firebase.corp.google.com/

**Comment by GabeWeiss** [comment]
Sorry, did that from the wrong chrome profile! Try https://console.firebase.google.com/?pli=1.
